name: Deploy Test

on:
  release:
    types: [published]

env:
  TF_VERSION: 0.14.7
  TG_VERSION: 0.26.7
  TG_SRC_PATH: terraform
  TFC_WORKSPACE: test
  TARGET_ENV: test

jobs:
  ci:
    name: Deploy Test
    runs-on: ubuntu-20.04
    environment: test

    steps:
      ### Get environment variables from AWS Parameter Store ###

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-duration-seconds: 900
          role-session-name: parks-reso-admin-test-gh-action
          role-skip-session-tagging: true

      # Admin variables
      - uses: "marvinpinto/action-inject-ssm-secrets@v1.2.1"
        with:
          ssm_parameter: "/parks-reso-admin/s3-bucket"
          env_variable_name: "S3_BUCKET"
      - uses: "marvinpinto/action-inject-ssm-secrets@v1.2.1"
        with:
          ssm_parameter: "/parks-reso-admin/origin-id"
          env_variable_name: "ORIGIN_ID"

      # API variables
      - uses: "marvinpinto/action-inject-ssm-secrets@v1.2.1"
        with:
          ssm_parameter: /parks-reso-api/origin-domain
          env_variable_name: "API_GATEWAY_ORIGIN_DOMAIN"
      - uses: "marvinpinto/action-inject-ssm-secrets@v1.2.1"
        with:
          ssm_parameter: /parks-reso-api/origin-id
          env_variable_name: "API_GATEWAY_ORIGIN_ID"
      - uses: "marvinpinto/action-inject-ssm-secrets@v1.2.1"
        with:
          ssm_parameter: /parks-reso-api/gateway-path-pattern
          env_variable_name: "API_GATEWAY_PATH_PATTERN"
          
    ### Upload functions to S3 ###

      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 10

      - name: Setting configEndpoint to true
        run: sed 's@localConfigEndpoint@'true'@g' src/env.js.template > src/env.js

      - name: Install and run build
        run: |
          npm i
          npm run build
        env:
          CI: true

      - name: Archive build
        if: success()
        uses: actions/upload-artifact@v1
        with:
          name: deploy_dist
          path: dist

      - name: Get release version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Deploy to Test S3
        env:
          s3_bucket: "${{ env.S3_BUCKET }}-${{ env.TARGET_ENV }}"
          dir_name: ${{ env.RELEASE_VERSION }}
        run: |
          aws s3 sync dist/ s3://$s3_bucket/$dir_name/


      ### Run Terragrunt ###

      - name: setup terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TF_VERSION }}
          cli_config_credentials_token: ${{ secrets.TFC_TEAM_TOKEN }}

      - uses: peter-murray/terragrunt-github-action@v1.0.0
        with:
          terragrunt_version: ${{ env.TG_VERSION }}

      - name: Terragrunt Apply
        working-directory: ${{ env.TG_SRC_PATH }}/${{ env.TFC_WORKSPACE }}
        env:
          app_version: ${{ env.RELEASE_VERSION }}
          s3_bucket: ${{ env.S3_BUCKET }}
          origin_id: ${{ env.ORIGIN_ID }}
          api_gateway_origin_domain: ${{ env.API_GATEWAY_ORIGIN_DOMAIN }}
          api_gateway_origin_id: ${{ env.API_GATEWAY_ORIGIN_ID }}
          api_gateway_path_pattern: ${{ env.API_GATEWAY_PATH_PATTERN }}
        run: terragrunt apply-all --terragrunt-non-interactive
