name: Linting & Unit Tests on PR

on: [pull_request]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-20.04
    environment: dev
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '10'
          cache: 'npm'
      - run: npm ci --ignore-scripts
      - run: npm run lint
  
  test:
    name: Test
    runs-on: ubuntu-20.04
    environment: dev
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '10'
          cache: 'npm'
      - run: npm ci --ignore-scripts
      - run: npm run test-ci